// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MoviezCenter/moviez/ent/genre"
	"github.com/MoviezCenter/moviez/ent/movie"
)

// GenreCreate is the builder for creating a Genre entity.
type GenreCreate struct {
	config
	mutation *GenreMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GenreCreate) SetName(s string) *GenreCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetTypeID sets the "type_id" field.
func (gc *GenreCreate) SetTypeID(u uint32) *GenreCreate {
	gc.mutation.SetTypeID(u)
	return gc
}

// AddMovieIDs adds the "movies" edge to the Movie entity by IDs.
func (gc *GenreCreate) AddMovieIDs(ids ...int) *GenreCreate {
	gc.mutation.AddMovieIDs(ids...)
	return gc
}

// AddMovies adds the "movies" edges to the Movie entity.
func (gc *GenreCreate) AddMovies(m ...*Movie) *GenreCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return gc.AddMovieIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (gc *GenreCreate) Mutation() *GenreMutation {
	return gc.mutation
}

// Save creates the Genre in the database.
func (gc *GenreCreate) Save(ctx context.Context) (*Genre, error) {
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GenreCreate) SaveX(ctx context.Context) *Genre {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GenreCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GenreCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GenreCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Genre.name"`)}
	}
	if _, ok := gc.mutation.TypeID(); !ok {
		return &ValidationError{Name: "type_id", err: errors.New(`ent: missing required field "Genre.type_id"`)}
	}
	return nil
}

func (gc *GenreCreate) sqlSave(ctx context.Context) (*Genre, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GenreCreate) createSpec() (*Genre, *sqlgraph.CreateSpec) {
	var (
		_node = &Genre{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(genre.Table, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(genre.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gc.mutation.TypeID(); ok {
		_spec.SetField(genre.FieldTypeID, field.TypeUint32, value)
		_node.TypeID = value
	}
	if nodes := gc.mutation.MoviesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.MoviesTable,
			Columns: genre.MoviesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GenreCreateBulk is the builder for creating many Genre entities in bulk.
type GenreCreateBulk struct {
	config
	err      error
	builders []*GenreCreate
}

// Save creates the Genre entities in the database.
func (gcb *GenreCreateBulk) Save(ctx context.Context) ([]*Genre, error) {
	if gcb.err != nil {
		return nil, gcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Genre, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GenreCreateBulk) SaveX(ctx context.Context) []*Genre {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GenreCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GenreCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
