// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/MoviezCenter/moviez/ent/review"
	"github.com/MoviezCenter/moviez/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescRating is the schema descriptor for rating field.
	reviewDescRating := reviewFields[1].Descriptor()
	// review.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	review.RatingValidator = func() func(float32) error {
		validators := reviewDescRating.Validators
		fns := [...]func(float32) error{
			validators[0].(func(float32) error),
			validators[1].(func(float32) error),
		}
		return func(rating float32) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
