-- Create "genres" table
CREATE TABLE "genres" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "type_id" integer NOT NULL, PRIMARY KEY ("id"));
-- Create "movies" table
CREATE TABLE "movies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "overview" character varying NOT NULL, "release_date" character varying NOT NULL, "poster_path" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "genre_movies" table
CREATE TABLE "genre_movies" ("genre_id" bigint NOT NULL, "movie_id" bigint NOT NULL, PRIMARY KEY ("genre_id", "movie_id"), CONSTRAINT "genre_movies_genre_id" FOREIGN KEY ("genre_id") REFERENCES "genres" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "genre_movies_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "reviews" table
CREATE TABLE "reviews" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "comment" character varying NOT NULL, "rating" real NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "movie_id" bigint NULL, "creator_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "reviews_movies_reviews" FOREIGN KEY ("movie_id") REFERENCES "movies" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "reviews_users_reviews" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
