name: CD

on:
  push:
    branches:
      - test/cicd-pipeline

env:
  ELASTIC_BEANSTALK_ENVIRONMENT: moviez-env
  ELASTIC_BEANSTALK_NAME: moviez

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: GOARCH=amd64 GOOS=linux go build -o bin/application .
      - name: Zip app for Elastic Beanstalk
        run: zip -r ${{github.run_id}}.zip bin Procfile config.yaml
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.run_id}}-${{github.sha}}
          path: ${{github.run_id}}.zip

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{github.run_id}}-${{github.sha}}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy to Elastic Beanstalk
        run: |
         # Create S3 bucket if it doesn't exist
          aws s3api head-bucket --bucket elasticbeanstalk-${{ vars.AWS_REGION }}-${{ vars.AWS_ACCOUNT_ID }} || aws s3 mb s3://elasticbeanstalk-${{ vars.AWS_REGION }}-${{ vars.AWS_ACCOUNT_ID }}
          
          # Continue with the existing commands
          aws s3 cp ${{github.run_id}}.zip s3://elasticbeanstalk-${{ vars.AWS_REGION }}-${{ vars.AWS_ACCOUNT_ID }}/$ELASTIC_BEANSTALK_ENVIRONMENT/
          aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label ${{ github.sha }} --source-bundle S3Bucket="elasticbeanstalk-${{ vars.AWS_REGION }}-${{ vars.AWS_ACCOUNT_ID }}",S3Key="$ELASTIC_BEANSTALK_ENVIRONMENT/${{github.run_id}}.zip"
          aws elasticbeanstalk update-environment --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENVIRONMENT --version-label ${{ github.sha }}
          aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENVIRONMENT
