// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
